word_list = [
    'merhaba', 'dünya', 'python', 'programlama', 'kitap', 'bilgisayar', 'masa', 'sandalye', 'gözlük', 'elma',
    'muz', 'şeftali', 'araç', 'yol', 'anahtar', 'kapı', 'pencere', 'bilim', 'matematik', 'tarih', 'müzik',
    'resim', 'güneş', 'ay', 'yıldız', 'bulut', 'yağmur', 'kar', 'rüzgar', 'deniz', 'göl', 'orman', 'dağ',
    'çiçek', 'ağaç', 'kuş', 'kedi', 'köpek', 'balık', 'at', 'eşek', 'inek', 'koyun', 'tavuk', 'horoz',
    'kamyon', 'otomobil', 'uçak', 'gemi', 'bisiklet', 'telefon', 'televizyon', 'bilgisayar', 'kalem', 'defter',
    'kitaplık', 'kırtasiye', 'sınıf', 'okul', 'hastane', 'doktor', 'hemşire', 'öğrenci', 'öğretmen', 'anne',
    'baba', 'kardeş', 'dede', 'nine', 'aile', 'ev', 'yatak', 'mutfak', 'banyo', 'oda', 'kapı', 'pencere',
    'perde', 'masa', 'sandalye', 'dolap', 'çanta', 'elbise', 'ayakkabı', 'saat', 'para', 'banka', 'alışveriş',
    'restoran', 'park', 'müze', 'sinema', 'tiyatro', 'spor', 'futbol', 'basketbol', 'yüzme', 'koşu', 'bisiklet',
    'tenis', 'yemek', 'kahvaltı', 'öğle', 'akşam', 'tatil', 'yaz', 'kış', 'ilkbahar', 'sonbahar', 'pilot', 'gazete',
    'radyo', 'internet', 'hava', 'ekran', 'yolcu', 'turist', 'gezi', 'tatil', 'renk', 'dil', 'yazılım', 'donanım',
    'elektrik', 'elektronik', 'bilgi', 'internet', 'sosyal', 'medya', 'oyun', 'eğitim', 'öğretim', 'kurs', 'yabancı',
    'ülke', 'dil', 'mühendis', 'mimar', 'avukat', 'hakim', 'savaş', 'barış', 'hayvan', 'bitki', 'gözlük', 'tıp',
    'hasta', 'eczane', 'yol', 'trafik', 'teknoloji', 'ses', 'müzik', 'resim', 'sergi', 'gösteri', 'konser',
    'film', 'kitap', 'roman', 'hikaye', 'şiir', 'masal', 'rüya', 'spor', 'futbol', 'basketbol', 'voleybol',
    'alışveriş', 'yemek', 'restoran', 'kahve', 'çay', 'tatlı', 'kek', 'tavuk', 'pizza', 'burger', 'pasta',
    'mevsim', 'yaz', 'kış', 'ilkbahar', 'sonbahar', 'doğa', 'güzel', 'kötü', 'hızlı', 'yavaş', 'sıcak',
    'soğuk', 'mutlu', 'üzgün', 'kırmızı', 'mavi', 'yeşil', 'sarı', 'turuncu', 'mor', 'siyah', 'beyaz'
]
